version: '3.8'

services:
  web-asso:
    build: .
    ports:
      - "8080:80" # On mappe le port 8080 de ton PC au port 80 du conteneur
    volumes:
      - ./src:/usr/share/nginx/html # "Lien magique" pour voir tes modifs sans red√©marrer